#!/bin/bash
# Check Unbound status on network change

case "$2" in
    up|vpn-up)
        systemctl restart unbound
        dig github.com @127.0.0.1 -p 53 +short || notify-send "Unbound: DNS failure"
        ;;
esac

