# ~/.GH/Qompass/Network/.github/workflows/fhp.yml
# -----------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

# .github/workflows/publish.yml
name: Publish to FlakeHub and validate

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake
        run: nix flake check
      - name: Build packages
        run: |
          nix build .#hash-utils
          nix build .#network-security-check
          nix build .#rage-setup

  publish-flakehub:
    needs: check
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: qompassai/network-security
          visibility: public
          rolling: ${{ !startsWith(github.ref, 'refs/tags/v') }}

